pkg/client: update waits to report lastError than the timed-out error
During an installation failure issue [1], the monitoring was reporting following error:
```
Error: running task Updating Grafana failed: waiting for Grafana Route to become ready failed: timed out waiting for the condition
```

`timed out waiting for the condition` does not indicate what was the last state that caused the wait to timeout. Reporting lastErr in cases of
timeout should provide better errors.

[1]: https://github.com/openshift/installer/issues/1219